# Python Dockerfile for local development
FROM python:3.7-alpine

# Install pip dependencies
ARG DEVELOPMENT
WORKDIR /app/
COPY requirements.txt dev-requirements.txt /app/
# apk dependencies below are needed for installing gevent
RUN apk --update add --virtual build-dependencies python-dev build-base && \
    pip install --upgrade pip && \
    pip install --upgrade --no-cache-dir -r requirements.txt && \
    if [ "$DEVELOPMENT" ]; then pip install --no-cache-dir -r dev-requirements.txt; fi && \
    apk del build-dependencies

RUN apk add --no-cache openssl

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

ENV PYTHONPATH=/app
# Use entr for auto-reloading on code changes
RUN apk --update add entr
CMD find /app -name \*.py -o -name \*.html | entr -r python /app/src/server.py
